spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:  jdbc:mariadb://training-server.cngnkphas7nb.us-east-1.rds.amazonaws.com:3306/vetdb
    username: admin
    password: welcome1